In [101]:
from dlshogi.data_loader import *
from cshogi import *

import numpy as np

In [102]:
sq = hflip_sq(C1)
SQUARE_NAMES[sq]

'9c'

In [103]:
b = Board()
m = b.move_from_usi('2h6h')
m16 = move16(m)
to_usi(m)

b'2h6h'

In [104]:
mf16 = hflip_move16(m)
mf = b.move_from_move16(mf16)
to_usi(mf)

b'8h4h'

## reorder

In [117]:
# flipped squares
hflip_squares = np.arange(81).reshape([9, 9])[::-1,:].flatten()

assert(len(hflip_squares) == 81)

hflip_squares 

array([72, 73, 74, 75, 76, 77, 78, 79, 80, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 54, 55, 56, 57, 58, 59, 60, 61, 62, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 36, 37, 38, 39, 40, 41, 42, 43, 44, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 18, 19, 20, 21, 22, 23, 24, 25, 26,  9, 10, 11, 12, 13,
       14, 15, 16, 17,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [121]:
sq = np.arange(81)
fsq = sq[hflip_squares]
fsq

array([72, 73, 74, 75, 76, 77, 78, 79, 80, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 54, 55, 56, 57, 58, 59, 60, 61, 62, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 36, 37, 38, 39, 40, 41, 42, 43, 44, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 18, 19, 20, 21, 22, 23, 24, 25, 26,  9, 10, 11, 12, 13,
       14, 15, 16, 17,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [122]:
fsq2 = fsq[hflip_squares]
fsq2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [123]:
sq == fsq2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [137]:
# flipped move labels (directions + hand pieces)

# move direction
hflip_direction = [
    UP, UP_RIGHT, UP_LEFT, RIGHT, LEFT, DOWN, DOWN_RIGHT, DOWN_LEFT, UP2_RIGHT, UP2_LEFT,
    UP_PROMOTE, UP_RIGHT_PROMOTE, UP_LEFT_PROMOTE, RIGHT_PROMOTE, LEFT_PROMOTE, DOWN_PROMOTE, DOWN_RIGHT_PROMOTE, DOWN_LEFT_PROMOTE, UP2_RIGHT_PROMOTE, UP2_LEFT_PROMOTE
]

assert(len(hflip_direction) == len(MOVE_DIRECTION))
assert(len(hflip_direction) == 20)

hflip_direction = np.array(hflip_direction + list(range(20, 27)))
hflip_direction

array([ 0,  2,  1,  4,  3,  5,  7,  6,  9,  8, 10, 12, 11, 14, 13, 15, 17,
       16, 19, 18, 20, 21, 22, 23, 24, 25, 26])

In [125]:
d = np.arange(20)
fd = d[hflip_direction]
fd

array([ 0,  2,  1,  4,  3,  5,  7,  6,  9,  8, 10, 12, 11, 14, 13, 15, 17,
       16, 19, 18])

In [126]:
fd2 = fd[hflip_direction]
fd2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
d == fd2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [129]:
hflip_idx  = np.repeat(hflip_direction, len(hflip_squares)) * 81 + np.tile(hflip_squares, len(hflip_direction))
hflip_idx

array([  72,   73,   74, ..., 1464, 1465, 1466])

### check

In [130]:
all(hflip_idx[hflip_idx[hflip_idx]] == hflip_idx)

True

In [131]:
np.where(hflip_idx[hflip_idx[hflip_idx]] != hflip_idx)

(array([], dtype=int64),)

### check 2

In [132]:
org = np.arange(81 * 20)
org

array([   0,    1,    2, ..., 1617, 1618, 1619])

In [133]:
flip = org[hflip_idx]
flip

array([  72,   73,   74, ..., 1464, 1465, 1466])

In [134]:
flip2 = flip[hflip_idx]
flip2

array([   0,    1,    2, ..., 1617, 1618, 1619])

In [135]:
flip2.reshape([20, 9, 9])

array([[[   0,    1,    2, ...,    6,    7,    8],
        [   9,   10,   11, ...,   15,   16,   17],
        [  18,   19,   20, ...,   24,   25,   26],
        ...,
        [  54,   55,   56, ...,   60,   61,   62],
        [  63,   64,   65, ...,   69,   70,   71],
        [  72,   73,   74, ...,   78,   79,   80]],

       [[  81,   82,   83, ...,   87,   88,   89],
        [  90,   91,   92, ...,   96,   97,   98],
        [  99,  100,  101, ...,  105,  106,  107],
        ...,
        [ 135,  136,  137, ...,  141,  142,  143],
        [ 144,  145,  146, ...,  150,  151,  152],
        [ 153,  154,  155, ...,  159,  160,  161]],

       [[ 162,  163,  164, ...,  168,  169,  170],
        [ 171,  172,  173, ...,  177,  178,  179],
        [ 180,  181,  182, ...,  186,  187,  188],
        ...,
        [ 216,  217,  218, ...,  222,  223,  224],
        [ 225,  226,  227, ...,  231,  232,  233],
        [ 234,  235,  236, ...,  240,  241,  242]],

       ...,

       [[1377, 1378, 137